version: '3.9'

services:
  django_app:
    build: .
    container_name: django_sqlite_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media

volumes:
  media_volume:
