# Generated by Django 4.2.20 on 2025-03-27 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[-a-zA-Z0-9_]+$"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.URLField(blank=True, max_length=256, null=True)),
                ("image", models.ImageField(upload_to="restaurant_images/")),
                ("rating", models.FloatField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
